### ISSUE TITLE
Home Assistant does not detect the activation and deactivation of the alarm

### ISSUE THREAD

**Issue by elax46** [twrecked/lovelace-hass-aarlo#115]
With the latest versions released when the alarm is activated (both via automations and alarm-panel) The alarm is activated (also from the arlo application it is active) but HA does not detect this activation and consequently the automations or manual deactivations do not work

**Comment by twrecked** [comment]
Sorry for the delay; you ever get this fixed?

**Comment by elax46** [comment]
don't worry no at the moment the automatic activation works the deactivation doesn't

**Comment by twrecked** [comment]
What is your `backed` set to? Try `sse` if it's [not set to it](https://github.com/twrecked/hass-aarlo#missing-events)

**Comment by elax46** [comment]
> What is your `backed` set to? Try `sse` if it's [not set to it](https://github.com/twrecked/hass-aarlo#missing-events)

This solution seems to work I will see later how it will go, for the moment I close
