### ISSUE TITLE
Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input)

### ISSUE THREAD

**Issue by Byrdks89** [twrecked/lovelace-hass-aarlo#120]
I am getting this error code when I try and access the live feed on my  camera.  The lovelace card shows recent at a glance pictures so I know its able to log in.

**Comment by twrecked** [comment]
I think Arlo just removed the RTSPS streams from their cameras. Can you using `direct` access, this will cause the lovelace card to bypass your home assistant device for the stream. See the [image options](https://github.com/twrecked/lovelace-hass-aarlo#image-options) section.

**Comment by Byrdks89** [comment]
Yes, I made that change and it seems to be working well. 

Thank you
