### ISSUE TITLE
Syntax error loading on Safari browser

### ISSUE THREAD

**Issue by jcollas** [twrecked/lovelace-hass-aarlo#13]
In v0.0.8

Seeing this in the debug console:  Safari doesn't show me the line number.  The card works fine in Google Chrome.

[Error] SyntaxError: Unexpected token ';'. Expected an opening '(' before a method's parameter list.
[Error] Unhandled Promise Rejection: /community_plugin/lovelace-hass-aarlo/hass-aarlo.js

**Comment by twrecked** [comment]
Are there any line numbers with those errors?

**Comment by twrecked** [comment]
Can you try 0.0.10 for the first error, I was using class fields which are experimental.

**Comment by jcollas** [comment]
Steve,

It works fine with 0.9.0 and 0.10.0.   Stupid safari/iOS

Thanks for making this component.  It’s a real win for me. 

:)

**Comment by twrecked** [comment]
I broke this one - I was tidying up all the errors PyCharm was showing me but I had enabled support for experimental features of Javascript.

Coding javascript is easy, keeping track of all the different standards, not so much!
