### ISSUE TITLE
Missing signal and battery from cards

### ISSUE THREAD

**Issue by Avatar1976** [twrecked/lovelace-hass-aarlo#138]
Latest home assistant release has seen battery and signal disappear from the cards.
Have confirmed they are still present on aarlo custom integration entities. Can't seem to get the card config to recognise signal and battery.

**Comment by OH010** [comment]
Same issue here.

**Comment by twrecked** [comment]
Can you paste your lovelace card config?

**Comment by Avatar1976** [comment]
> Can you paste your lovelace card config?
> 
> edit: and what do you mean disappear?
Config follows:
`
type: custom:aarlo-glance
entities:
  - entity: camera.aarlo_beneath_dwelling
    name: Beneath Delling
image_click: stream
image_view: direct
image_top: name,status
image_bottom: motion,library,signal,snapshot,battery
`
![Screenshot_20230207_172648_Home Assistant](https://user-images.githubusercontent.com/47725430/217165310-b6a71bee-c812-47cd-b56a-fa67c85dc466.jpg)

**Comment by Avatar1976** [comment]
> Can you paste your lovelace card config?
> 
> edit: and what do you mean disappear?

Let me know if you need more examples

**Comment by twrecked** [comment]
That's perfect. And it's a pretty simple config.

The next question is what is showing for the value of `sensor.aarlo_battery_level_beneath_dwelling`? Look in `Developer Tools --> STATES`.

Another quick one to try might be to force the backend to `sse` if it already isn't. You can add this to your `aarlo` config.

```yaml
aarlo:
  backend: sse
```

**Comment by Avatar1976** [comment]
![Screenshot_20230208_075514_Home Assistant](https://user-images.githubusercontent.com/47725430/217363610-74f52c92-c113-4ef5-97c4-d598f5ecad10.jpg)
You may have just hit the nail on the head.
Will try the modification to the aarlo config as you suggest and report back.

**Comment by Avatar1976** [comment]
Swapped out the back end as you suggested. 
Also wondered is it possible to get the front end config to read the attributes of the camera entity as per screenshot below. 
![Screenshot_20230208_081002_Home Assistant](https://user-images.githubusercontent.com/47725430/217366687-b1f86f77-5a96-4fc3-b4af-c642faad6507.jpg)

**Comment by twrecked** [comment]
Do you have admin access enabled on the shared account? Sometimes Arlo will turn it off, you need it for the battery devices.

Can you try the latest 0.7 version? It has some improvements in tracking states of devices, I noticed _Arlo_ had changed their URL calls again.

I'll look into the other thing, I'm not sure how it works at the moment.

**Comment by Avatar1976** [comment]
> Do you have admin access enabled on the shared account? Sometimes Arlo will turn it off, you need it for the battery devices.

Definitely admin

> Can you try the latest 0.7 version? It has some improvements in tracking states of devices, I noticed _Arlo_ had changed their URL calls again.

Have updated to the latest version of aarlo, is there a new release of your Lovelace card?

**Comment by OH010** [comment]
I just noticed that my "sensor:
  - platform: aarlo
    monitored_conditions:"
code was under a second (duplicate) "sensor" line in my config.yaml. I moved the -platform, monitored conditions etc. under the main "sensor:" section and voila, the battery and other missing items became visible. 
This could have been the reason for my issue but could also been something else, as I remove and update all arlo packages.

**Comment by twrecked** [comment]
@OH010  Chances are that is it, something similar happened in another issue, you can only have one of each setting section.

**Comment by Avatar1976** [comment]
Yep was trying to configure statistics platform and had a secondary sensor heading for that.

**Comment by Avatar1976** [comment]
Fixed now apologies for raising something that was a problem of my own making.
duplicate sensor sections was the exact issue.

**Comment by twrecked** [comment]
Glad it's working and have a good weekend.

**Comment by Avatar1976** [comment]
> Glad it's working and have a good weekend.

Thanks twrecked!  You too buddy
