### ISSUE TITLE
Visual Issue when playing videos

### ISSUE THREAD

**Issue by gcorgnet** [twrecked/lovelace-hass-aarlo#14]
Hi,

I really like the new video player with the "stop" function but I seem to be getting an issue with it (see below)

Hope that helps

![image](https://user-images.githubusercontent.com/4731735/62665339-ff5bfc80-b9d2-11e9-84e4-a7ca8eeb847a.png)

**Comment by twrecked** [comment]
I just fixed that. I wasn't closing an image element.
