### ISSUE TITLE
Options to remove fields

### ISSUE THREAD

**Issue by bdf0506** [twrecked/lovelace-hass-aarlo#15]
Screen real estate is a problem, especially on Mobile devices. Would be nice if you could actually hide the Title, Date Snapshot, and State. Yes you can put them on the top instead of the bottom, but would also make sense if you can physically hide them.

**Comment by twrecked** [comment]
I just checked in a possible fix. You can add this to the config to hide the entries:

```yaml
hide:
  - status
  - date
  - title
```

**Comment by twrecked** [comment]
I'm assuming this is working!
