### ISSUE TITLE
Custom element doesn't exist: aarlo-glance

### ISSUE THREAD

**Issue by rsaffi** [twrecked/lovelace-hass-aarlo#18]
Hi,

I am running home-assistant `0.102.1` on venv and installed `lovelace-hass-aarlo` via HACS. I can see the JS file under `/home/homeassistant/.homeassistant/www/community/lovelace-hass-aarlo/hass-aarlo.js`.
I use Lovelace in GUI mode, so I went to the Raw config editor and added the following to the top:

```
resources:
  - type: module
    url: /community/lovelace-hass-aarlo/hass-aarlo.js
```

Saved and restarted home-assistant, but not only I don't have a aarlo-glance card option when trying to add a new card, but even if I go to Manual Card I can't use the `custom:aarlo-glance` card type:

![image](https://user-images.githubusercontent.com/15200226/69476526-4da6d700-0ddb-11ea-8000-a33f48d79bce.png)

I have checked and re-checked all the configurations and everything seems to be in order. The JS file doesn't seem to be loaded at all by Lovelace. I have also tried the following to no avail:

```
resources:
  - type: module
    url: /local/community/lovelace-hass-aarlo/hass-aarlo.js
```

Am I missing something or is there something really wrong? I tried to check if I could get to the file via `curl`, but no matter what I try I always get a HTTP 200, even for URIs that don't exist at all. :-(

**Comment by twrecked** [comment]
It might need an `_plugin` in the URL:

```yaml
  - type: module
    url: /community_plugin/lovelace-hass-aarlo/hass-aarlo.js
```

I'll check where the discrepancy came from.

**Comment by rsaffi** [comment]
I don't think so, as a folder `community_plugin` doesn't exist within my home-assistant installation:

```
(homeassistant) homeassistant@homeserver ~ $ find /home/homeassistant/ -type d -iname "community" 
/home/homeassistant/.homeassistant/www/community

(homeassistant) homeassistant@homeserver ~ $ find /srv/homeassistant/ -type d -iname "community" 
(homeassistant) homeassistant@homeserver ~ $ 
```

That said, if I reference the plugin using the `community_plugin` folder, it'll resolve to a non-existing path on my system.

**Comment by twrecked** [comment]
Did you try?

**Comment by rsaffi** [comment]
> Did you try?
I hadn't, but now I have. I'll be damned: it worked.
I stand corrected and apologize for that. I simply thought it wouldn't work not only because I couldn't find `community_plugin` folder inside my HA installation, but also because during my searches I had come across [this](https://www.reddit.com/r/homeassistant/comments/cunpjv/custom_element_doesnt_exist_aarloglance/exy0hid/), from someone else that stumbled upon the same problem.

Thank you very much for the quick response, solving my issue, @twrecked! :-)

**Comment by twrecked** [comment]
No worries and glad it's all working now. The `community` directory used to used directly but I guess HACS does something internally with the URL.

I hope it works well for you and ideas for improvement always accepted!
