### ISSUE TITLE
Playback of videos not working when within Android Companion App

### ISSUE THREAD

**Issue by gcorgnet** [twrecked/lovelace-hass-aarlo#20]
Hi,

I have been using this lovelace plugin successfully for a long time now and recently installed the Official Android Companion App for Home Assistant.

I have noticed that when I load my Arlo Camera recording from within the aoo, the playback is not working (the image just stays frozen when clicking on "play").

Note: Playing recordings works perfectly on the same android device if loaded from the normal browser (or as PWA)

Is there anything you can think of that could be causing this?

**Comment by twrecked** [comment]
I've just downloaded the app and have the same issue.

The big difference is the video format. Live streaming uses HLS streaming, via the home assistant site, and library playback uses MP4 directly from the Arlo website. I'm guessing one of a few things:
* the app isn't expecting mp4
* or the app isn't trusting the source
* or there is some mangling between the HTML video player and APP

I'll check the JS code here but it might be useful asking the app developers if they support MP4.

**Comment by sdrapha** [comment]
Hi, for me, while I have perfect smooth playback using Brave browser, all the other apps in my phone have playback issues including: HACompanion App, Firefox, Opera Touch, Via browser, HA WallPanel. They all hang, untill I click multiple times to get the controls to show, pausing and playing it again to actually start playing and you always miss the firsts frames.
I wonder if all those apps use the system webviewer while Brave has a different one🤔?(just guessing)

**Comment by twrecked** [comment]
Still looking at this. Although I'm rather limited in what I can do because of how streaming works. Maybe the direct option with mpeg-dash works.

**Comment by twrecked** [comment]
Can you try again with the latest Lovelace release. I just moved to the companion App (which I really like by the way) and it's working well for me.

**Comment by twrecked** [comment]
Closing because I moved to the Android app and it should be working. Feel free to re-open it.
