### ISSUE TITLE
New "light" attribute

### ISSUE THREAD

**Issue by sbowater** [twrecked/lovelace-hass-aarlo#22]
I have two Arlo security lights set up in HA that are near two of my Arlo cameras.  I added the "light: light.arlo_xxxx" attribute to the glance card for the corresponding camera but can't see any difference to the content of the card.  What does this do?

**Comment by twrecked** [comment]
That's all you need to add and you will get a lightbulb icon appearing at the bottom right of the card. You might need to make sure the card is updated, try CTRL+R on the page.

It look like this:
![light](https://user-images.githubusercontent.com/47094394/74384724-f273f780-4dbf-11ea-90f7-ce23077726c2.png)

**Comment by sbowater** [comment]
Right now I have a date/time stamp for last capture in that spot. Do I need to get rid of that?

**Comment by twrecked** [comment]
You shouldn't have to get rid of it, mine works with the `image_date` turned on but give it a go.

Could you send me the card config for one of your cameras and I'll try it here? And what web browser are you viewing this on?

**Comment by sbowater** [comment]
Thanks.  I'm using Chrome Version 80.0.3987.100 (Official Build) (64-bit).  I tried both clearing the cache and making sure that the Lovelace view was refreshed.

Card config for one of the cameras is as follows:
<pre><code>
- type: 'custom:aarlo-glance'
  entity: camera.aarlo_side
  name: Side
  image_click: play
  show:
    - motion
    - sound
    - snapshot
    - battery_level
    - signal_strength
    - captured_today
    - image_date
  top_date: false
  top_status: true
  top_title: true
  light: light.aarlo_security_light_side
</code></pre>

Image from Lovelace:
![Annotation 2020-02-12 201202](https://user-images.githubusercontent.com/59455316/74395087-01fd3b80-4dd4-11ea-9f30-34adf1432335.png)

**Comment by twrecked** [comment]
It fails the same way here. I'll take a look.

And if that's snow, me and you have very similar outsides!

**Comment by twrecked** [comment]
I think I found it!

**Comment by twrecked** [comment]
I just pushed a new release, this lets you add the following to your card config, this will put the light bulb on the left.

```
  light_left: true
```

**Comment by sbowater** [comment]
I haven't had a lot of time to try the feature you just added, but the latest update did allow me to see the light and I also commented out all of the top_* attributes to get default behavior and it looks good so I may not mess with it any more.  Thanks for doing this!

**Comment by twrecked** [comment]
You ever get this working fully? 

Is it ok to close this?

**Comment by sbowater** [comment]
Feel free to close.  I actually changed my settings so that I'm using
mostly defaults and it looks/works fine.

**Comment by twrecked** [comment]
Thanks - glads it working!
