### ISSUE TITLE
No live stream

### ISSUE THREAD

**Issue by blair287** [twrecked/lovelace-hass-aarlo#23]
Everything is working apart from live streaming i can see motion and sound alerts etc and recording but if I click on the image it acts like its playing ie the stop button is present but there is no live stream just a still image.

Ive read the posts mentioned on this issue but unsure what version im running and if this is even possible im running the windows virtual box version and will soon be moving to a intel nuc install will only be home assistant installed will it work there?

**Comment by twrecked** [comment]
What kind of cameras are you trying to stream with? The Arlo Q ones don't seem to stream. There is an issue in the `stream:` component. Do you have `stream:` enabled?

**Comment by rafuz** [comment]
It stopped streming for me too but I can't find any valuable error anywhere.
I am using Arlo Pro cameras.


```
arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | Europe/Rome
version | 0.105.3
virtualenv | false

```

**Comment by twrecked** [comment]
It's still working for me - as ever. Do you have traces like this - the `userStreamActive`? 

```
2020-02-13 11:45:42 DEBUG (ArloEventStream) [pyaarlo] Front Camera CAMERA got one cameras/4XH4757HA5C98
2020-02-13 11:45:42 DEBUG (ArloEventStream) [pyaarlo] set:4XH4757HA5C98/activityState=userStreamActive
2020-02-13 11:45:43 DEBUG (MainThread) [pyaarlo] url=rtsps://vzwow87-z1-prod.ar.arlo.com:443/vzmodulelive/XXXXXXXXXXXXXXXX
2020-02-13 11:45:43 INFO (MainThread) [homeassistant.components.stream] Started stream: rtsps://vzwow87-z1-prod.ar.arlo.com:443/vzmodulelive/XXXXXXXXXXXXXX
```

**Comment by guedeaux** [comment]
Streaming is not working for me. They have worked for months, but I noticed a while back that they weren't streaming.

When clicking on the card, the card looks like it is streaming (sensors go away, and stop button appears in lower left corner) but the image remains as it was. I checked the log, and I do see the userStreamActive traces you listed. I am using the first gen arlo cameras.

**Comment by twrecked** [comment]
Can you try again? I broke it it 0.6.18.8. It should be fixed in the newest release.

**Comment by guedeaux** [comment]
Yes, it now works in 0.6.18.9. Thanks!

**Comment by twrecked** [comment]
Fixed!
