### ISSUE TITLE
Custom element doesn't exist: hass-aarlo.

### ISSUE THREAD

**Issue by MechEng70** [twrecked/lovelace-hass-aarlo#25]
Installed the aarlo camera support and the lovelace hass aarlo from the HACS store.

Checked the RAW UI:
resources:
  - type: module
    url: /hacsfiles/lovelace-battery-entity/battery-entity.js
  - type: module
    url: /hacsfiles/lovelace-hass-aarlo/hass-aarlo.js

The following error:

`**Custom element doesn't exist: hass-aarlo.**
type: 'custom:hass-aarlo'
entity: camera.aarlo_front_door
name: Front Door
show:
  - motion
  - sound
  - snapshot
  - battery_level
  - signal_strength
  - captured_today
  - image_date`

Thoughts?

**Comment by twrecked** [comment]
Which version of HACS?

And my cards are included using

```html
  - url: /community_plugin/lovelace-hass-aarlo/hass-aarlo.js
    type: module
```

Sorry for the short reply. I'm on my phone...

**Comment by MechEng70** [comment]
HACS 0.23.2
I did update it to community_plugin
Cleared the cache, quit chrome and restarted. 
Still get the red box saying that the element does not exist. 

Appreciate the fast response.

**Comment by twrecked** [comment]
Try

```
type: 'custom:aarlo-glance'
```

**Comment by MechEng70** [comment]
That did it!

**Comment by twrecked** [comment]
Excellent. I updated the docs to make it clearer. The card type name pre-dates the HACS installation mechanism.
