### ISSUE TITLE
Error: Custom element not found: aarlo-glance

### ISSUE THREAD

**Issue by MaartenMees** [twrecked/lovelace-hass-aarlo#32]
Hi, bought new arlo cameras. So I installed the aarlo integration (needed to update my hassio to the newest version). But can't seem to install lovelace-hass-aarlo. Always the same error. (Error: Custom element not found: aarlo-glance). I tried installing it via HACS and manually but nothing. Please help! :)

**Comment by twrecked** [comment]
Can you send me your aarlo-glance config? And can you try reloading? Sometimes the UI can cache aggressively.

**Comment by MaartenMees** [comment]
Hi, thanks for the quick response. I notice the update broke more then only this integration. First I need to fix everything and see if the problem persists. Will let you know. Thank you

**Comment by MaartenMees** [comment]
okay, everything is back to normal. But still the problem is their. with everything I try, I get custom element not found ... :( (At the moment installed with hacs)

**Comment by twrecked** [comment]
Can you paste an example of your hass-aarlo config?

The easiest way to track this down is with a web browser debugger. Open the debug tools - on Chrome type CTRL+SHIFT+I and then reload (CTRL+SHIFT+R) a page with a camera on it. Under the network tab you should see a `hass-aarlo.js` entry. This will show us the file is being loaded.

The other place to look would be the `console` tab.

If you can find the directory of the hass-aarlo.js file that will help.

**Comment by MaartenMees** [comment]
Hi, as for configuration. I tried the example one from github with my cameras entity. 

web browser debugger shows it's get loaded (it's there with the rest of my plugins)

the directory of hass-aarlo.js is /local/plugins/hass-aarlo.js

thanks

**Comment by MaartenMees** [comment]
Hi,

There was an new update today, after installing that, everything works fine.

Thank you!

**Comment by twrecked** [comment]
Excellent news. Truthfully, there a lot of the pieces of the card that I have no control over so I'm glad it worked out!
