### ISSUE TITLE
refresh image/preview when motion or sound is detected

### ISSUE THREAD

**Issue by Megachip** [twrecked/lovelace-hass-aarlo#35]
Any possiblity to refresh the (preview)image of the glace when a movement (or sound) is detected?

Seems sensors are almost live, but the picture and date of the last capture didn't update until I replay the capture or create a snapshot.

**Comment by twrecked** [comment]
I reproduced that here. I can see the media update coming from Arlo but nothing happening on the card.

I will take a look.

**Comment by twrecked** [comment]
I'm closing this - the card code was updated and the snapshot code in `hass-aarlo` component has been improved.

Feel feel to re-open if it doesn't work.
