### ISSUE TITLE
video does not play when clicking image

### ISSUE THREAD

**Issue by chuckakung** [twrecked/lovelace-hass-aarlo#40]
I have hass-aarlo and lovelace-hass-arlo installed.  When I click on captured clips, I get the gallery view.  When i click on an image, the audio plays but no video, just the still image.  Not getting errors or warnings in the logs.  Is this a known problem?

my install is on mac os x, python virtual env.
Thanks

**Comment by twrecked** [comment]
Yes. If you have newer cameras thay have a codec that can't be handled by all platforms.

See [here](https://github.com/twrecked/hass-aarlo/issues/151#issuecomment-660261197) for more info.

We tracked this down recently and I haven't had chance to update the docs.

**Comment by twrecked** [comment]
Nice find. And I guess it does change it.

I really need to get at least one of the newer cameras so I can test this stuff better.

**Comment by ssilence5** [comment]
The reason this works is that the video gets downgraded to 1080p when it is normally recorded as 2K. 2K and 4K videos for arlo are encoded as HEVC which is a format that most browsers can’t play. But it does work fine on the iPhone as it supports this format.

**Comment by twrecked** [comment]
I'm going to close this one but keep an eye on it.
