### ISSUE TITLE
hls.min.js.map resource not found (error 404)

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [twrecked/lovelace-hass-aarlo#45]
When I load my Home Assistant Lovelace interface with the Aarlo Glance card in Chrome Developer Tools, I get the following error:

`DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/hls.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

I am not sure if this is because I am running Home Assistant behind a reverse proxy but if I take the above URL and paste it into my address bar, I get:

`Failed to resolve the requested file.`

I am guessing this could also be loosely linked to other users being unable to view their streams?

Integration: 0.7.0-beta.2
JS Module: 0.1.4.1

**Comment by twrecked** [comment]
I see the same thing and it's because we're running the developer tools. I don't think it matters, see [here](https://stackoverflow.com/questions/18499930/missing-map-resource/18499985).

The streaming issue is caused by the `stream` component. Did you try direct streaming yet?

**Comment by danieledwardgeorgehitchcock** [comment]
Yeah just tried the live stream.. No issues with that!

Closing as this doesn't relate to a bug with the Aarlo card
