### ISSUE TITLE
Arlo Ultra Battery Level Always 0%

### ISSUE THREAD

**Issue by shehandavy** [twrecked/lovelace-hass-aarlo#46]
I have six Arlo Ultra cameras running, and the battery_level on all cameras are shown as 0% although the actual battery level is close to 100% on all cameras. 

Screenshot below:
![Screenshot_20200813-211749](https://user-images.githubusercontent.com/8924093/90128708-a6276580-ddaa-11ea-9e34-6de5a3fcbff8.jpg)

Developer Tools shows correct battery percentage:
![Screenshot_20200813-212021](https://user-images.githubusercontent.com/8924093/90128916-0a4a2980-ddab-11ea-9f18-0cffb068bc3f.jpg)

**Comment by twrecked** [comment]
Did you:

- Enable the `battery_level` [sensor](https://github.com/twrecked/hass-aarlo#sensor-configuration)?
  It needs this sensor to work.
- Rename you battery device? Then add a `battery_id` fields to the `aarlo-glance` card with this name.
- Give your account admin access? Then please do, it seems to need it.

**Comment by shehandavy** [comment]
Wow I hadn't enabled the battery_level sensor. Added it and restarted HA. Works perfectly now! 

Thank you so much and kudos for the great work you're doing. Keep it up! 👍

Closing the issue.

**Comment by twrecked** [comment]
Excellent, glad it's working now.
