### ISSUE TITLE
Arlo Video Doorbell 1:1 Aspect Ratio

### ISSUE THREAD

**Issue by larsstaa** [twrecked/lovelace-hass-aarlo#51]
I have implemented the Arlo Video Doorbell. The problems is that the Arlo Video Doorbell has a different ratio then other Arlo cameras. The video doorbell has aspect Ratio of 1:1 with resolution 1536x1536, 1080x1080 or 720x720. When clicking to see the last recordings, the 3x3 grid overview chop off the top and bottom clips. The same problem with aspect ratio is also when streaming directly from the small window without fullscreen, but that is not so noticeable as the last clip grid 3x3 overview.
Would it be possible to add a setting in the Configuration where we can choose what type of camera we have and the aspect ratio gets adjusted?

![Arlo Video Doorbell](https://user-images.githubusercontent.com/40205822/94208277-c2e6ab00-fec9-11ea-95c9-c4782cd9a4e6.JPG)

**Comment by twrecked** [comment]
I'll take a look.

Truthfully, javascaript/css/html isn't my strong point but I think I can figure something out.

**Comment by larsstaa** [comment]
Thank you, that's sound great. And thank you for the amazing work on the hass-aarlo integration :-)

**Comment by twrecked** [comment]
The support is experimental but can you try the [latest release](https://github.com/twrecked/lovelace-hass-aarlo/releases/tag/v0.1.5). Add the following to your doorbell card config:

```yaml
aspect_ratio: square
```

**Comment by larsstaa** [comment]
I can confirm that it is works perfect :)

**Comment by twrecked** [comment]
Thanks for the update.

**Comment by twrecked** [comment]
@larsstaa  A favour - this [question](https://github.com/twrecked/hass-aarlo/issues/335) came in. I don't have a video doorbell, can you confirm the things he mentioned work? Thanks!

**Comment by larsstaa** [comment]
@twrecked I am out traveling, but will try it upcoming weekend. Have not tried to detect the button on dorbell, but motion sensor and live stream is working.

**Comment by Backslashh** [comment]
@larsstaa Thanks for the reply!
Good to know that the motion sensor and live stream works. I assume these show up by default without any further configuration.
If you can let me know about the button press that would be amazing.

Also, does this integration require a hub to work with the video doorbell at all?

**Comment by Backslashh** [comment]
@larsstaa also, do you need the Arlo subscription for this to work?

**Comment by larsstaa** [comment]
Questions answered in other post: https://github.com/twrecked/hass-aarlo/issues/335
