### ISSUE TITLE
Error on Android phone but works on laptop and fire HD 10

### ISSUE THREAD

**Issue by chuddnutts** [twrecked/lovelace-hass-aarlo#62]
I have updated the integrations but having an issue with viewing the cameras on my mobile phone (android). It is working fine in my laptop, Amazon fire HD10 with no issue. I just keep getting this on my phone
![Screenshot_20210203_231123_io homeassistant companion android](https://user-images.githubusercontent.com/17237803/106957046-688b1000-672f-11eb-9b7a-0db663e3b208.jpg)

I have deleted the app, cleared the cache etc... Any ideas?

**Comment by twrecked** [comment]
This is 0.2? I guess that replaceAll function is not there.

Which version of Android and which browser?

**Comment by chuddnutts** [comment]
It's Android 10. App version 2021.1.1 - Full

If I open HA in the chrome browser on the phone it works, as does it on my windows laptop using IE or Chrome and Fire HD 10

It just seems to be the HA Companion app on the phone which is the issue.

**Comment by twrecked** [comment]
I think the replaceAll() call is too new and I don't think all apps support it. I'll push a fix later today.

I'll install the app and try that too.

**Comment by twrecked** [comment]
Can you try alpha.5; it doesn't need the replaceAll() call.

**Comment by chuddnutts** [comment]
You are an absolute superstar, whatever you did has fixed it. I am using alpha6 now for your reference. 

Thank you

**Comment by twrecked** [comment]
Excellent, I'll close this now. And thanks for trying out the alpha.

And if you are on 6 you should be able to swipe left and right on the library view on your phone.

**Comment by chuddnutts** [comment]
I can firm that the swipe left/right is working a treat. I have noticed that when clicking on the clip you need to press pause and they play for the video to play. It's no issue but just thought I would let you know..

Thank you for your help @twrecked

**Comment by twrecked** [comment]
Is the "pause then play" in the Home Assistant app? It's working ok for me in Chrome.

**Comment by chuddnutts** [comment]
Yes this is in the HA android app. I have just tried it on chrome from the phone and it works perfect from there.

**Comment by twrecked** [comment]
Autoplay in the app might work now.
