### ISSUE TITLE
If there are no recent videos in library storage, empty grid shows with no "X" to close & return to previous view

### ISSUE THREAD

**Issue by rpitera** [twrecked/lovelace-hass-aarlo#70]
**Version Info:**
lovelace-hass-arlo version Info: v0.2-alpha.9
Version | core-2021.2.2
Installation Type | Home Assistant OS
Host Operating System | Home Assistant OS 5.11
Supervisor Version | supervisor-2021.02.6
Docker Version | 19.03.13
Chrome Version 88.0.4324.150 (Official Build) (64-bit)

**Issue:**
When clicking on captured icon for a camera entity that has recordings,  gird of videos displays normally with pagination and close buttons available.  But if there are no videos in storage, for example for a new camera or for a camera that's been relocated and has no captures. only an empty grid displays without any control buttons provided.  Only way to return to the camera snapshot view is to do a refresh or shift+refresh from the browser.

**Expected Behavior:**
Some kind of text message stating there are no recent captures and (at the least) a close button.

**Screen shot of issue:**
![aarlo](https://user-images.githubusercontent.com/19910294/107535657-f1220a00-6b8e-11eb-93c9-e627e08dd314.jpg)

**Comment by twrecked** [comment]
Thanks for testing!

I'll probably make it so you can't open the library if there is nothing to show.

**Comment by rpitera** [comment]
I'm grateful for something to test!  Like the rewrite and new features, this is really the only bug I found so far.

IMHO, not being able to open the library without some kind of user feedback might be prone to frustration.  I like the idea of showing a simple message replacing the grid; this way the user at least knows why the button "isn't working", but I'll defer to your reasoning.

**Comment by twrecked** [comment]
All input gratefully accepted. I might start with a simpler option and add a full message later. I'm teaching myself all this stuff as I go along!

**Comment by rpitera** [comment]
Just updated and I really like the way you addressed this issue.  Perfect solution; icon indicates status and the overlay message reinforces it.  Thanks!

**Comment by twrecked** [comment]
Thanks, and glad you liked it!

**Comment by rpitera** [comment]
Said this to you a long time ago when you first started this integration and it's still true; it makes Arlo cams worth running.  The functionality this extends to HA made me stick with the platform.  I recommend it to everyone who'll listen.  Thanks again for your tireless work making this better and better.  Cheers!

**Comment by TheDK** [comment]
I feel the same way. The image and service quality of Arlo cams do not justify the imo rather steep price. But the integration into HA built by Steve and the general simplicity (ie storage...) makes it worth it. Next step: Arlo Smart capabilites, I will try to have a look into the event stream asap...
