### ISSUE TITLE
No Sound Icon in 

### ISSUE THREAD

**Issue by admeno** [twrecked/lovelace-hass-aarlo#80]
Running 
lovelace-hass-arlo v0.2-alpha.13
aarlo  0.7.1.beta.1

On the new view it  didnt show the sound-icon. On the old-view it works fine.
Here is my aarlo lovelace card-config:

```
type: 'custom:aarlo-glance'
entity: camera.aarlo_einfahrt
name: Einfahrt
image_view: direct
image_top: 'name,date,status'
image_bottom: 'motion,library,snapshot,battery,signal,on_off,sound'
image_click: stream
library_sizes: '3,4,2'
library_view: download
```

**Comment by twrecked** [comment]
Should be fixed by alpha.14.

I'd managed to forget to update certain options in the new config checking.
