### ISSUE TITLE
wsLoadLibrary failed {err}

### ISSUE THREAD

**Issue by sparks3875392** [twrecked/lovelace-hass-aarlo#93]
Hi,
I seem to get this error if Arlo has a problem with a camera - E.g. When the Arlo camera has gone offline in the Arlo app  I have this error raised in a popup in the Safari browser repeating for each camera that is offline. Does that sound likely or do I have a config issue?

Thanks!

**Comment by twrecked** [comment]
It's a piece of test code I forgot to remove. I'll do it later and release a new version.

**Comment by twrecked** [comment]
Should be in 0.2.0b2.

**Comment by sparks3875392** [comment]
Works great on my install.

**Comment by Megachip** [comment]
Still get it on 0.2.0b5 :(

**Comment by twrecked** [comment]
Can you check `hass-aarlo` actually updated? Home Assistant will aggressively cache JavaScript files.

You might need to force a reload - `CTRL+SHIFT+I` to get to developer tools and `CTRL+SHIFT+R` to reload everything.
