### ISSUE TITLE
"wsStopStream failed" at end of video

### ISSUE THREAD

**Issue by maalgorium** [twrecked/lovelace-hass-aarlo#94]
Hi. Recently (sorry, not sure when it started. A week or two ago?) I started getting a popup dialog that says "wsStopStream failed [object Object]" when a video stops, either by reaching the end or pressing the stop button. This happens on latest Chrome and Safari on OS X 11.2.3.  HA is core-2021.3.4 and Lovelace Hass Aarlo is v0.2.0b3. I don't see anything in the JS console at the time of the message. Everything otherwise works fine as far as I can tell. Let me know if this is a config problem or if I can help diagnose it.

**Comment by twrecked** [comment]
It's debug code. I'll move it into a log (where I should have put it to start with!)

**Comment by twrecked** [comment]
Should be removed in 0.2.0b4.

**Comment by twrecked** [comment]
Assumed fixed...
